import Head from 'next/head'
import { Login } from '../../components'

export default function AdminDashboard() {
  return (
    <>
      <Head>
        <title>Admin | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={'w-full h-[100vh]'}>
        <Login user='admin' />
      </main>
    </>
  )
}
