import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={'w-full h-[100vh] flex items-center justify-center'}>
         {/* Coming soon */}
          <p className="text-2xl text-gray-500">Coming soon!</p>
      </main>
    </>
  )
}
