import Head from 'next/head'
import { Login } from '../../components'
import { useStateValue } from '../../context/StateProvider'

export default function AdminDashboard() {
    const [{user}, dispatch] = useStateValue()
  return (
    <>
      <Head>
        <title>Admin | Organizer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={'w-full h-[100vh]'}>
        {
            user ? <h1>Organizer Dashboard</h1> : <Login user='organizer' />
        }
      </main>
    </>
  )
}
